services:
  - type: web
    name: r-tam
    runtime: node
    buildCommand: npm install && cd backend && npm install
    startCommand: npm start
envVars:
  - key: PORT
    value: 10000
  - key: NODE_ENV
    value: production
